package test.fuelapp;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Label;
import javafx.scene.control.Separator;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Objects;

/**
 * Class to handle the backend of the profile fxml page
 */
public class ProfileController {
    SQLiteLink sqLiteLink = new SQLiteLink();
    private DatabaseOperations databaseOperations = new DatabaseOperations();
    private String currentUsername = LoginController.current_user;

    private String userBookmarks;

    @FXML
    private Label label_profile_username;
    @FXML
    private Label label_fuel_type;
    @FXML
    private Label label_fuel_efficiency;
    @FXML
    private Label label_latitude;
    @FXML
    private Label label_longitude;
    @FXML
    private Label label_max_distance;

    @FXML
    private VBox vbox_fav_stations;

    @FXML
    private Label label_current_user;


    /**
     * Initialise page by loading the current user's details and showing their bookmarks
     * @throws SQLException If database cannot be accessed
     */
    @FXML
    public void initialize() throws SQLException{
        label_current_user.setText(LoginController.current_user);
        loadUserDetailsProfile();
        displayBookmarks();
    }


    /**
     * Using the user interface, load it with the current user's details from the database
     */
    public void loadUserDetailsProfile() {
        IUser user = databaseOperations.getUserDetails(currentUsername);
        if (user != null) {
            label_profile_username.setText(String.valueOf(user.getName()));
            label_fuel_type.setText(String.valueOf(user.getFuelType()));
            label_fuel_efficiency.setText(String.valueOf(user.getFuelEfficiency()));
            label_latitude.setText(String.valueOf(user.getLatitude()));
            label_longitude.setText(String.valueOf(user.getLongitude()));
            label_max_distance.setText(String.valueOf(user.getMaxTravelDistance()));
            userBookmarks = String.valueOf(user.getBookmark());
        }
    }


    /**
     * Convert the string of bookmarks generated by the user interface to a usable form and display them
     * @throws SQLException If database cannot be accessed
     */
    public void displayBookmarks() throws SQLException {
        // Create array of users bookmarks
        String[] rawBookmarks = userBookmarks.replaceAll("\\[", "").replaceAll("\\]", "").replaceAll("\\s", "").split(",");
        ArrayList<String> bookmarkArray = new ArrayList<String>();
        Collections.addAll(bookmarkArray, rawBookmarks);

        // Clear all previous bookmarked stations
        vbox_fav_stations.getChildren().clear();
        vbox_fav_stations.getChildren().add(new Separator());

        // For every bookmarked station fetch the stations name and current fuel price
        for (int displayBookmarkCounter = 0; displayBookmarkCounter < bookmarkArray.size(); displayBookmarkCounter++){
            String bookmarkLabelText = databaseOperations.fetchBookmarks(Integer.parseInt(bookmarkArray.get(displayBookmarkCounter)));
            // Ignore base data
            if (Objects.equals(bookmarkLabelText, "null - 0.0")){continue;}

            // Create and style new label to display data
            Label label = new Label(bookmarkLabelText);
            label.setStyle("-fx-font-size: 20;");
            label.setFont(Font.font("SansSerif"));
            label.setTextFill(Color.web("#344E41"));
            vbox_fav_stations.getChildren().add(label);
            vbox_fav_stations.getChildren().add(new Separator());
        }
    }


    /**
     * Redirect to the settings page, allowing user to edit their data
     * @param event Triggers when the 'Edit Details' button is pressed
     */
    public void toSettings(ActionEvent event) {
        sqLiteLink.changeScene(event, "Settings.fxml", "Settings");
    }


    /**
     * Redirect to the login page, and log user out
     * @param event Triggers when the logout button is pressed
     */
    @FXML
    public void LogOut(ActionEvent event) {
        sqLiteLink.changeScene(event, "LogInPage.fxml", "Log In");
    }


    /**
     * Redirect to David's fuel efficiency calculator
     */
    @FXML
    public void goToCalculator() {
        // For now, just display an alert
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setTitle("Calculator");
        alert.setHeaderText(null);
        alert.setContentText("Calculator button clicked");
        alert.showAndWait();
    }


    /**
     * Redirect to map page
     * @param event Trigger when the user presses the map menu button
     */
    @FXML
    public void goToMap(ActionEvent event) {
        sqLiteLink.changeScene(event, "LandingPage.fxml", "Map");
    }


    /**
     * Redirect to the compare page
     * @param event Trigger when the user presses the compare page menu button
     */
    @FXML
    public void goToComparePage(ActionEvent event) {
        sqLiteLink.changeScene(event, "PricePage.fxml", "Compare Page");
    }
}
